// This file was automatically generated by "pack_hip"

#pragma once

#include <stdlib.h>

#if defined(__GNUC__)
#  pragma GCC diagnostic push
#  pragma GCC diagnostic ignored "-Wunused-variable"
#endif

#ifdef __cplusplus
extern "C" {
#endif

extern const char kernels_gfx90a[];
static const size_t kernels_gfx90a_size_uncompressed = 1376968;
static const size_t kernels_gfx90a_size_compressed = 168184;

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__)
#  pragma GCC diagnostic pop
#endif
