/**
 * pack_hip.c: Pack the precompiled gfx90a code object for redistribution
 *
 * The AMD counterpart of pack.c, and deliberately much simpler.
 *
 * pack.c has to split the CUDA blob into per-entry PTX because the driver JITs
 * that text at run time, and compiling all ~650 kernels to load one of them
 * costs seconds. A HIP code object is already machine code: hipModuleLoadData
 * relocates it and hands back function handles, so there is nothing to split
 * and no per-kernel compilation to defer. One blob, loaded once.
 *
 * Input is the UNBUNDLED ELF, not hipcc's --genco output. --genco emits a
 * clang offload bundle (magic "CCOB" once compressed), and while recent HIP
 * runtimes unwrap those, the raw code object is accepted by every version and
 * removes a runtime-version dependency we cannot test without an MI210. The
 * Makefile runs clang-offload-bundler to extract it.
 *
 * Output is kernels_gfx90a.lz4 plus kernels_hip.h. Kept out of kernels.h
 * because that file is regenerated wholesale by pack.c from kernels_75.ptx,
 * which is not in the repository -- running pack.c to add an AMD symbol would
 * mean regenerating the CUDA artifacts too.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <lz4hc.h>

static char *read_file(const char *fname, size_t *size_out) {
    FILE *f = fopen(fname, "rb");
    if (!f) {
        fprintf(stderr, "pack_hip: could not open '%s'!\n", fname);
        exit(EXIT_FAILURE);
    }

    fseek(f, 0, SEEK_END);
    size_t size = ftell(f);
    fseek(f, 0, SEEK_SET);

    char *buf = (char *) malloc(size);
    if (fread(buf, size, 1, f) != 1) {
        fprintf(stderr, "pack_hip: could not read '%s'!\n", fname);
        exit(EXIT_FAILURE);
    }

    fclose(f);
    *size_out = size;
    return buf;
}

int main(int argc, char **argv) {
    const char *arch = (argc > 1) ? argv[1] : "gfx90a";

    char in_fname[256], out_fname[256], sym[256];
    snprintf(in_fname,  sizeof(in_fname),  "kernels_%s.elf", arch);
    snprintf(out_fname, sizeof(out_fname), "kernels_%s.lz4", arch);
    snprintf(sym,       sizeof(sym),       "kernels_%s", arch);

    size_t size;
    char *data = read_file(in_fname, &size);

    // A code object always starts with the ELF magic. Catch the easy mistake of
    // packing the bundle instead of its contents, which would load as garbage.
    if (size < 4 || memcmp(data, "\177ELF", 4) != 0) {
        fprintf(stderr,
                "pack_hip: '%s' is not an ELF object -- did you forget to run "
                "clang-offload-bundler --unbundle?\n", in_fname);
        exit(EXIT_FAILURE);
    }

    int bound = LZ4_compressBound((int) size);
    char *buf = (char *) malloc(bound);
    int compressed = LZ4_compress_HC(data, buf, (int) size, bound,
                                     LZ4HC_CLEVEL_MAX);
    if (compressed <= 0) {
        fprintf(stderr, "pack_hip: compression failed!\n");
        exit(EXIT_FAILURE);
    }

    FILE *f2 = fopen(out_fname, "wb");
    if (!f2) {
        fprintf(stderr, "pack_hip: could not open '%s'!\n", out_fname);
        exit(EXIT_FAILURE);
    }
    fwrite(buf, 1, compressed, f2);
    fclose(f2);

    FILE *f = fopen("kernels_hip.h", "w");
    if (!f) {
        fprintf(stderr, "pack_hip: could not open 'kernels_hip.h'!\n");
        exit(EXIT_FAILURE);
    }

    fprintf(f, "// This file was automatically generated by \"pack_hip\"\n\n");
    fprintf(f, "#pragma once\n\n");
    fprintf(f, "#include <stdlib.h>\n\n");
    fprintf(f, "#if defined(__GNUC__)\n");
    fprintf(f, "#  pragma GCC diagnostic push\n");
    fprintf(f, "#  pragma GCC diagnostic ignored \"-Wunused-variable\"\n");
    fprintf(f, "#endif\n\n");
    fprintf(f, "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");
    fprintf(f, "extern const char %s[];\n", sym);
    fprintf(f, "static const size_t %s_size_uncompressed = %zu;\n", sym, size);
    fprintf(f, "static const size_t %s_size_compressed = %d;\n\n", sym,
            compressed);
    fprintf(f, "#ifdef __cplusplus\n}\n#endif\n\n");
    fprintf(f, "#if defined(__GNUC__)\n");
    fprintf(f, "#  pragma GCC diagnostic pop\n");
    fprintf(f, "#endif\n");
    fclose(f);

    printf("pack_hip: %s -> %s (%zu -> %d bytes, %.1f%%)\n", in_fname,
           out_fname, size, compressed, 100.0 * compressed / (double) size);

    free(buf);
    free(data);
    return EXIT_SUCCESS;
}
